sudo: false

before_install:
 - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

language: scala

scala:
  - 2.12.2
  - 2.11.11

env:
  - PLATFORM=JVM
  - PLATFORM=JS

jdk:
  - oraclejdk8

script:
  - if [ "$PLATFORM" == "JS" ]; then
      sbt ++$TRAVIS_SCALA_VERSION surfaceJS/test;
      sbt ++$TRAVIS_SCALA_VERSION airframeJS/test;
    else  
      sbt ++$TRAVIS_SCALA_VERSION project$PLATFORM/test;      
    fi

jobs:
  include:
    - stage: after_script
      script:
        -  sbt ++$TRAVIS_SCALA_VERSION "; coverage; project$PLATFORM/test; coverageReport";
           sbt coverageAggregate && bash <(curl -s https://codecov.io/bash);
      scala: 2.12.2	   
      env: PLATFORM=JVM
