sudo: false

language: scala

scala:
  - 2.12.1
  - 2.11.8

jdk:
  - oraclejdk8

script:
  - if [ "$TRAVIS_SCALA_VERSION" == "2.12.1" ]; then
      sbt ++$TRAVIS_SCALA_VERSION airframeJS/test;
      sbt ++$TRAVIS_SCALA_VERSION "; project airframeJVM; coverage; test; coverageReport";
      sbt coverageAggregate coveralls;
    else
      sbt ++$TRAVIS_SCALA_VERSION airframeJS/test;
      sbt ++$TRAVIS_SCALA_VRRSION airframeJVM/test;
    fi
