sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
    - $HOME/nvm

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

language: scala

matrix:
  include:
  # Code format test
  - env: SCALA_VERSION=2.12.3 PROJECT=code-format
    jdk: oraclejdk8
    script: ./scalafmt --test
  - env: SCALA_VERSION=2.12.3 PROJECT=projectJVM
    jdk: oraclejdk8
    script:
      - ./sbt ++$SCALA_VERSION "; coverage; ${PROJECT}/test; coverageReport"
      - ./sbt coverageAggregate && bash <(curl -s https://codecov.io/bash)
  - env: SCALA_VERSION=2.12.3 PROJECT=logJS
    jdk: oraclejdk8
    script: ./sbt ++$SCALA_VERSION ${PROJECT}/test
  - env: SCALA_VERSION=2.12.3 PROJECT=surfaceJS
    jdk: oraclejdk8
    script: ./sbt ++$SCALA_VERSION ${PROJECT}/test
  - env: SCALA_VERSION=2.12.3 PROJECT=airframeJS
    jdk: oraclejdk8
    script: ./sbt ++$SCALA_VERSION ${PROJECT}/test
  - env: SCALA_VERSION=2.11.11 PROJECT=projectJVM
    jdk: oraclejdk8
    script: ./sbt ++$SCALA_VERSION ${PROJECT}/test
  - env: SCALA_VERSION=2.12.3 PROJECT=docs
    jdk: oraclejdk8
    before_install:
      - export PATH=${PATH}:./vendor/bundle
    install:
      - rvm use 2.2.3 --install --fuzzy
      - gem update --system
      - gem install sass
      - gem install jekyll -v 3.2.1
    script:
      - pwd
      - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
          ./sbt ^^0.13.16 docs/publishMicrosite;
        fi
