sudo: false

language: scala

scala:
  - 2.12.1
  - 2.11.8

env:
  - PROJECT=airframeJS
  - PROJECT=airframeJVM

jdk:
  - oraclejdk8

script:
  - if [ "$TRAVIS_SCALA_VERSION" == "2.12.1" -a "$PROJECT" == "airframeJVM" ]; then
      sbt ++$TRAVIS_SCALA_VERSION "; coverage; $PROJECT/test; coverageReport";
      sbt coverageAggregate coveralls;
    elif [ "$PROJECT" == "airframeJS" ]; then
      sbt ++$TRAVIS_SCALA_VERSION $PROJECT/test:fastOptJS;
      sbt ++$TRAVIS_SCALA_VERSION $PROJECT/test;
    else
      sbt ++$TRAVIS_SCALA_VERSION $PROJECT/test;
    fi
