sudo: false

before_install:
 - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

language: scala

scala:
  - 2.12.2
  - 2.11.11

env:
  - PLATFORM=JVM PROJECT=project
  - PLATFORM=JS PROJECT=surface
  - PLATFORM=JS PROJECT=airframe

jdk:
  - oraclejdk8

script:
  - if [ "$TRAVIS_SCALA_VERSION" == "2.12.2" -a "$PLATFORM" == "JVM" ]; then
      sbt ++$TRAVIS_SCALA_VERSION "; coverage; project${PLATFORM}/test; coverageReport";
      sbt coverageAggregate && bash <(curl -s https://codecov.io/bash);
    else
      sbt ++$TRAVIS_SCALA_VERSION ${project}${PLATFORM}/test;
    fi

matrix:
  exclude:
  - scala: 2.11.11
    env: PLATFORM=JS PROJECT=surface
  - scala: 2.11.11
    env: PLATFORM=JS PROJECT=surface
