name: Airframe
baseurl: /airframe
description: Best Practice of Building Service Objects in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.19-SNAPSHOT
org: docs
markdown: kramdown
